<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSFML" Version="2.5.0" />
    <PackageReference Include="SFML.Net" Version="2.5.0" />
  </ItemGroup>
    
    <ItemGroup>
        <None Remove="assets/Backgrounds/*.png" />
        <EmbeddedResource Include="assets/Backgrounds/*.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <None Remove="assets/MainMenu/*.png" />
        <EmbeddedResource Include="assets/MainMenu/*.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <None Remove="assets/tilesets/*.png" />
        <EmbeddedResource Include="assets/tilesets/*.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>
    
    <ItemGroup>
        <None Remove="assets/fonts/*.ttf" />
        <EmbeddedResource Include="assets/fonts/*.ttf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <None Remove="assets/sounds/*.ogg" />
        <EmbeddedResource Include="assets/sounds/*.ogg">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <None Remove="assets/sounds/*.wav" />
        <EmbeddedResource Include="assets/sounds/*.wav">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>
</Project>
